# STEP 5  Analyse
Final analyse, stats and filter list

In [4]:
import requests 
import bs4 as bs 
import time, json, random
import pandas as pd 
import csv 
data = pd.read_csv("HKFastFood-withHealth-noFiber.csv")

,Unnamed: 0,Unnamed: 0.1,Calories,Calories_From_Fat,Calories_From_Protein,Calories_From_Carb,Total_Fat,Saturated_Fat,Trans_Fat,Cholesterol,...,Sodium_PDV,Total_Carbohydrates_PDV,Dietary_Fiber_PDV,Protein_PDV,Vitamin_A_PDV,Vitamin_C_PDV,Calcium_PDV,Iron_PDV,Health_Rating,Taste_Rating
count,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.0,79.000000,...,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000
mean,161.341772,161.341772,184.050633,74.968354,42.582278,66.227848,8.398734,2.594937,0.0,29.050633,...,16.810127,5.569620,6.835443,21.291139,-6572.113924,-6571.746835,-6324.860759,-6324.898734,60.113924,82.417722
std,92.701324,92.701324,82.586691,51.286797,25.135840,50.282267,5.616699,2.087932,0.0,22.116764,...,6.300338,4.229577,7.418671,12.567920,4786.220290,4786.685611,4855.211606,4855.158818,22.976570,13.247745
min,12.000000,12.000000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,7.000000,38.000000
25%,69.000000,69.000000,140.000000,37.500000,28.000000,24.000000,4.250000,1.000000,0.0,15.000000,...,13.000000,2.000000,0.000000,14.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,43.000000,78.500000
50%,160.000000,160.000000,180.000000,70.000000,40.000000,64.000000,7.000000,2.000000,0.0,20.000000,...,18.000000,5.000000,4.000000,20.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,59.000000,87.000000
75%,236.500000,236.500000,230.000000,90.000000,50.000000,104.000000,10.000000,3.500000,0.0,45.000000,...,22.000000,9.000000,8.000000,25.000000,3.000000,3.000000,4.000000,7.000000,80.500000,91.000000
max,313.000000,313.000000,410.000000,220.000000,144.000000,196.000000,24.000000,11.500000,0.0,100.000000,...,25.000000,16.000000,40.000000,72.000000,180.000000,130.000000,32.000000,20.000000,100.000000,100.000000

In [7]:
#data that is NOT OK for all groups of people
stat=data[(data['USA_Female_Below_40%DV']=="N") & (data['USA_Male_Below_40%DV']=='N')&(data['China_Female_Below_40%DV']=='N')\
& (data['China_Male_Below_40%DV']=="N") & (data['Europe_Female_Below_40%DV']=='N')&(data['Europe_Male_Below_40%DV']=='N')].describe()

stat

,Unnamed: 0,Unnamed: 0.1,Calories,Calories_From_Fat,Calories_From_Protein,Calories_From_Carb,Total_Fat,Saturated_Fat,Trans_Fat,Cholesterol,...,Sodium_PDV,Total_Carbohydrates_PDV,Dietary_Fiber_PDV,Protein_PDV,Vitamin_A_PDV,Vitamin_C_PDV,Calcium_PDV,Iron_PDV,Health_Rating,Taste_Rating
count,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000,...,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000
mean,168.220930,168.220930,585.046512,258.244186,116.953488,212.255814,28.703488,10.125000,0.273256,90.930233,...,56.668605,17.691860,15.581395,58.476744,-4519.000000,-4517.808140,-4050.436047,-4054.970930,45.813953,85.383721
std,103.179728,103.179728,253.718586,146.765592,57.884116,124.823261,16.135732,6.308382,0.533426,71.090387,...,22.398584,10.402617,12.671712,28.942058,5006.550113,5007.657163,4942.319467,4938.518083,21.685693,11.294742
min,0.000000,0.000000,190.000000,25.000000,20.000000,0.000000,3.000000,1.500000,0.000000,0.000000,...,3.000000,0.000000,0.000000,10.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,7.000000,47.000000
25%,79.750000,79.750000,410.000000,160.000000,72.000000,144.000000,18.000000,5.000000,0.000000,50.000000,...,44.750000,12.000000,8.000000,36.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,29.000000,80.000000
50%,158.000000,158.000000,531.500000,232.000000,108.000000,180.000000,26.000000,9.000000,0.000000,73.000000,...,51.500000,15.000000,12.000000,54.000000,3.000000,0.000000,8.000000,15.000000,40.000000,88.000000
75%,265.500000,265.500000,705.000000,321.000000,152.000000,273.000000,36.000000,13.250000,0.500000,101.250000,...,63.000000,23.000000,16.000000,76.000000,16.000000,25.000000,26.250000,25.000000,64.000000,93.000000
max,334.000000,334.000000,1770.000000,990.000000,392.000000,684.000000,110.000000,37.000000,2.500000,505.000000,...,151.000000,57.000000,64.000000,196.000000,180.000000,400.000000,100.000000,50.000000,91.000000,100.000000

### Create "short lists" of healthier choices (ok-list.csv) & bad choices (avoid-food.csv)

In [8]:
#save list to file
subSet=data[(data['USA_Female_Below_40%DV']=="Y") & (data['USA_Male_Below_40%DV']=='Y')&(data['China_Female_Below_40%DV']=='Y')\
& (data['China_Male_Below_40%DV']=="Y") & (data['Europe_Female_Below_40%DV']=='Y')&(data['Europe_Male_Below_40%DV']=='Y')]
subSet.to_csv("ok-food.csv")



subSet=data[(data['USA_Female_Below_40%DV']=="N") & (data['USA_Male_Below_40%DV']=='N')&(data['China_Female_Below_40%DV']=='N')\
& (data['China_Male_Below_40%DV']=="N") & (data['Europe_Female_Below_40%DV']=='N')&(data['Europe_Male_Below_40%DV']=='N')]
subSet.to_csv("avoid-food.csv")
subSet

,Unnamed: 0,Unnamed: 0.1,Brand,Product,Link,Category,Serving_Size,Calories,Calories_From_Fat,Calories_From_Protein,...,Iron_PDV,Ingredients,Health_Rating,Taste_Rating,USA_Female_Below_40%DV,USA_Male_Below_40%DV,China_Female_Below_40%DV,China_Male_Below_40%DV,Europe_Female_Below_40%DV,Europe_Male_Below_40%DV
0,0,0,Five Guys,Bacon Burger,https://fastfoodnutrition.org/five-guys/bacon-...,Burgers,279g,780,460.0,172.0,...,-9999.0,We are working on getting the ingredients for ...,47,92,N,N,N,N,N,N
1,1,1,Five Guys,Bacon Cheeseburger,https://fastfoodnutrition.org/five-guys/bacon-...,Burgers,317g,920,560.0,204.0,...,-9999.0,We are working on getting the ingredients for ...,38,94,N,N,N,N,N,N
2,2,2,Five Guys,Cheeseburger,https://fastfoodnutrition.org/five-guys/cheese...,Burgers,303g,840,500.0,188.0,...,-9999.0,We are working on getting the ingredients for ...,29,94,N,N,N,N,N,N
3,3,3,Five Guys,Hamburger,https://fastfoodnutrition.org/five-guys/hamburger,Burgers,265g,700,400.0,156.0,...,-9999.0,We are working on getting the ingredients for ...,33,91,N,N,N,N,N,N
5,5,5,Five Guys,Little Bacon Cheeseburger,https://fastfoodnutrition.org/five-guys/little...,Burgers,204g,630,350.0,104.0,...,-9999.0,We are working on getting the ingredients for ...,29,93,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,329,329,Subway,Spicy Italian Flatizza,https://fastfoodnutrition.org/subway/spicy-ita...,Flatizza,181g,490,220.0,100.0,...,15.0,We are working on getting the ingredients for ...,55,85,N,N,N,N,N,N
331,331,331,Subway,Cheese & Veggies Pizza,https://fastfoodnutrition.org/subway/cheese-ve...,Pizzas,381g,740,230.0,144.0,...,30.0,We are working on getting the ingredients for ...,50,68,N,N,N,N,N,N
332,332,332,Subway,Cheese Pizza,https://fastfoodnutrition.org/subway/cheese-pizza,Pizzas,293g,680,200.0,128.0,...,30.0,We are working on getting the ingredients for ...,42,91,N,N,N,N,N,N
333,333,333,Subway,Pepperoni Pizza,https://fastfoodnutrition.org/subway/pepperoni...,Pizzas,323g,790,290.0,152.0,...,30.0,We are working on getting the ingredients for ...,47,86,N,N,N,N,N,N
334,334,334,Subway,Sausage Pizza,https://fastfoodnutrition.org/subway/sausage-p...,Pizzas,336g,820,310.0,156.0,...,30.0,We are working on getting the ingredients for ...,27,70,N,N,N,N,N,N

### Below are statistic of food in different restaurants

In [27]:
#% of healthy food in one resautrant
Brand="KFC"
All=data[(data['Brand']==Brand)]
Part=data[(data['Brand']==Brand) & (data['USA_Female_Below_40%DV']=="Y") & (data['USA_Male_Below_40%DV']=='Y')&(data['China_Female_Below_40%DV']=='Y')\
& (data['China_Male_Below_40%DV']=="Y") & (data['Europe_Female_Below_40%DV']=='Y')&(data['Europe_Male_Below_40%DV']=='Y')]

print(Brand+" has "+str(round(len(Part)/len(All)*100, 2))+"% healthier food")
All[['Calories','Total_Fat','Sugars','Sodium','Dietary_Fiber']].describe()

KFC has 39.58% healthier food

          Calories  Total_Fat     Sugars       Sodium  Dietary_Fiber
count    48.000000  48.000000  48.000000    48.000000      48.000000
mean    341.979167  19.145833   2.750000   883.541667       1.479167
std     252.948022  14.083323   7.015181   581.090280       2.021055
min      15.000000   0.000000   0.000000    10.000000       0.000000
25%     157.500000   7.000000   0.000000   410.000000       0.000000
50%     275.000000  17.500000   0.000000   765.000000       1.000000
75%     510.000000  28.000000   2.250000  1312.500000       3.000000
max    1100.000000  61.000000  40.000000  2270.000000      10.000000

In [28]:
#% of healthy food in one resautrant
Brand="McDonald's"
All=data[(data['Brand']==Brand)]
Part=data[(data['Brand']==Brand) & (data['USA_Female_Below_40%DV']=="Y") & (data['USA_Male_Below_40%DV']=='Y')&(data['China_Female_Below_40%DV']=='Y')\
& (data['China_Male_Below_40%DV']=="Y") & (data['Europe_Female_Below_40%DV']=='Y')&(data['Europe_Male_Below_40%DV']=='Y')]

print(Brand+" has "+str(round(len(Part)/len(All)*100, 2))+"% healthier food")
All[['Calories','Total_Fat','Sugars','Sodium','Dietary_Fiber']].describe()

McDonald's has 15.07% healthier food

          Calories   Total_Fat     Sugars       Sodium  Dietary_Fiber
count    73.000000   73.000000  73.000000    73.000000      73.000000
mean    521.301370   26.712329  11.671233  1027.671233       2.863014
std     310.086264   19.124213  14.972247   615.217375       1.766313
min     140.000000    3.000000   0.000000    20.000000       0.000000
25%     350.000000   15.000000   3.000000   680.000000       2.000000
50%     460.000000   24.000000   7.000000   990.000000       2.000000
75%     550.000000   32.000000  12.000000  1210.000000       3.000000
max    1770.000000  110.000000  72.000000  3630.000000       8.000000

In [29]:
#% of healthy food in one resautrant
Brand="Five Guys"
All=data[(data['Brand']==Brand)]
Part=data[(data['Brand']==Brand) & (data['USA_Female_Below_40%DV']=="Y") & (data['USA_Male_Below_40%DV']=='Y')&(data['China_Female_Below_40%DV']=='Y')\
& (data['China_Male_Below_40%DV']=="Y") & (data['Europe_Female_Below_40%DV']=='Y')&(data['Europe_Male_Below_40%DV']=='Y')]

print(Brand+" has "+str(round(len(Part)/len(All)*100, 2))+"% healthier food")
All[['Calories','Total_Fat','Sugars','Sodium','Dietary_Fiber']].describe()

Five Guys has 10.71% healthier food

         Calories  Total_Fat     Sugars       Sodium  Dietary_Fiber
count   28.000000  28.000000  28.000000    28.000000      28.000000
mean   525.464286  35.714286   5.571429   845.571429       1.214286
std    171.629766  11.629646   4.709554   428.206287       1.100745
min    220.000000  15.000000   0.000000    50.000000       0.000000
25%    418.750000  26.000000   1.000000   572.500000       0.000000
50%    526.500000  34.000000   8.000000   865.500000       2.000000
75%    626.250000  42.250000   9.000000  1115.000000       2.000000
max    920.000000  62.000000  14.000000  1700.000000       3.000000

In [30]:
#% of healthy food in one resautrant
Brand="Subway"
All=data[(data['Brand']==Brand)]
Part=data[(data['Brand']==Brand) & (data['USA_Female_Below_40%DV']=="Y") & (data['USA_Male_Below_40%DV']=='Y')&(data['China_Female_Below_40%DV']=='Y')\
& (data['China_Male_Below_40%DV']=="Y") & (data['Europe_Female_Below_40%DV']=='Y')&(data['Europe_Male_Below_40%DV']=='Y')]

print(Brand+" has "+str(round(len(Part)/len(All)*100, 2))+"% healthier food")
All[['Calories','Total_Fat','Sugars','Sodium','Dietary_Fiber']].describe()

Subway has 20.0% healthier food

          Calories  Total_Fat     Sugars       Sodium  Dietary_Fiber
count    90.000000  90.000000  90.000000    90.000000      90.000000
mean    473.777778  18.016667   8.955556  1205.166667       5.477778
std     275.218311  14.254991   6.242139   663.912666       3.474555
min      50.000000   1.000000   1.000000    65.000000       1.000000
25%     230.000000   8.000000   4.000000   735.000000       3.000000
50%     410.000000  14.000000   6.000000  1110.000000       4.000000
75%     695.000000  26.000000  14.000000  1470.000000       9.000000
max    1160.000000  62.000000  36.000000  3040.000000      16.000000

In [31]:
#% of healthy food in one resautrant
Brand="Pizza Hut"
All=data[(data['Brand']==Brand)]
Part=data[(data['Brand']==Brand) & (data['USA_Female_Below_40%DV']=="Y") & (data['USA_Male_Below_40%DV']=='Y')&(data['China_Female_Below_40%DV']=='Y')\
& (data['China_Male_Below_40%DV']=="Y") & (data['Europe_Female_Below_40%DV']=='Y')&(data['Europe_Male_Below_40%DV']=='Y')]

print(Brand+" has "+str(round(len(Part)/len(All)*100, 2))+"% healthier food")
All[['Calories','Total_Fat','Sugars','Sodium','Dietary_Fiber']].describe()

Pizza Hut has 29.17% healthier food

         Calories  Total_Fat     Sugars       Sodium  Dietary_Fiber
count   96.000000  96.000000  96.000000    96.000000      96.000000
mean   309.791667  14.739583   3.354167   816.875000       1.750000
std    151.601827   8.241416   2.525571   364.782019       0.984084
min     80.000000   3.000000   0.000000   230.000000       0.000000
25%    210.000000   9.000000   2.000000   550.000000       1.000000
50%    280.000000  13.000000   2.000000   750.000000       2.000000
75%    370.000000  19.000000   5.000000  1002.500000       2.000000
max    850.000000  48.000000  12.000000  2140.000000       5.000000